import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const blogPostsDir = path.join(__dirname, '../src/blog-posts');
const outputFilePath = path.join(__dirname, '../src/data/blogPosts.ts');

async function generateBlogPosts() {
  const files = fs.readdirSync(blogPostsDir).filter(file => file.endsWith('.tsx'));
  const blogPosts = [];

  for (const file of files) {
    const filePath = path.join(blogPostsDir, file);
    const content = fs.readFileSync(filePath, 'utf8');

    const idMatch = content.match(/id:\s*['"](.*?)['"]/);
    const titleMatch = content.match(/title:\s*['"](.*?)['"]/);
    const dateMatch = content.match(/date:\s*['"](.*?)['"]/);
    const readTimeMatch = content.match(/readTime:\s*['"](.*?)['"]/);
    const categoryMatch = content.match(/category:\s*['"](.*?)['"]/);
    const authorMatch = content.match(/author:\s*['"](.*?)['"]/);

    // Extract content from <p> tags for dynamic excerpt
    const pTagContent = content.match(/<p>[\s\S]*?<\/p>/g);
    let dynamicExcerpt = '';
    if (pTagContent) {
      dynamicExcerpt = pTagContent.map(p => p.replace(/<p>|<\/p>/g, '').trim()).join(' ');
      dynamicExcerpt = dynamicExcerpt.substring(0, 150) + (dynamicExcerpt.length > 150 ? '...' : '');
    }

    if (idMatch && titleMatch && dateMatch && readTimeMatch && categoryMatch && authorMatch) {
      blogPosts.push({
        id: idMatch[1],
        title: titleMatch[1],
        excerpt: dynamicExcerpt,
        date: dateMatch[1],
        readTime: readTimeMatch[1],
        category: categoryMatch[1],
        author: authorMatch[1],
        component: `() => import('../blog-posts/${file}').then(module => ({ default: module.default.content }))`,
      });
    }
  }

  const outputContent = `// This file is auto-generated by a script. Do not edit manually.\nimport { BlogPost } from '../types/blog';\n\nconst blogPosts: BlogPost[] = [\n${blogPosts.map(post => `  {\n    id: \`${post.id}\`,\n    title: \`${post.title.replace(/`/g, '\`')}\`,\n    excerpt: \`${post.excerpt.replace(/`/g, '\`')}\`,\n    content: ${post.component},\n    date: \`${post.date.replace(/`/g, '\`')}\`,\n    readTime: \`${post.readTime.replace(/`/g, '\`')}\`,\n    category: \`${post.category.replace(/`/g, '\`')}\`,\n    author: \`${post.author.replace(/`/g, '\`')}\`,\n  },`).join('\n')}\n];\n\nexport default blogPosts;\n`;

  fs.writeFileSync(outputFilePath, outputContent, 'utf8');
  console.log('src/data/blogPosts.ts generated successfully!');
}

generateBlogPosts();