name: CI/CD

on:
  push:
    branches: [main] # Deploy only on push to main branch
  pull_request:
    branches: [main]

jobs:
  build-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Run ESLint
        run: pnpm lint

      - name: Run Prettier check
        run: pnpm format --check

  deploy:
    needs: build-and-lint # This job depends on the build-and-lint job
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' # Only deploy if pushing to main branch

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true # Checkout submodules

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Deploy to GitHub Pages
        run: pnpm deploy
